### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by bencha** [NikolaiRadke/NOKO#10]
Hallo an alle,

hat jemand einen Tip wo ich den Akku bestellen kann?

Danke für eure Hilfe und
viele Grüße
Benjamin

**Comment by NikolaiRadke** [comment]
Im Auktionshaus des Vertrauens. Z.B. hier:
http://www.ebay.de/itm/LiPo-Akku-2000-mAh-3-7-V-Lithium-Polymer-Schutzschaltung-/182347325476?hash=item2a74bf6024:g:jXUAAOSw37tV9Tio

Darauf achten, dass der Akku eine Schutzschaltung (PCM) hat!

**Comment by bencha** [comment]
Hallo Nikolai,

danke für den Link und den Hinweis "Schutzschaltung (PCM)".


Grüße
Ben
