### ISSUE TITLE
NOKO_EEPROM_Disk0.ino lässt sich nach Anleitung nicht kompilieren

### ISSUE THREAD

**Issue by d1ckb31n** [NikolaiRadke/NOKO#11]
Der Sketch NOKO_EEPROM_Disk0.ino lässt sich nach dem auskommentieren von def_stories nicht mehr fehlerfrei kompilieren.

"Die Zeile #define def_stories 1 // Stories on SD card? auskommentieren. Das geht, indem man // an den Anfang der Zeile setzt."

Fehler:

NOKO-master\src\NOKO_EEPROM_Disk0\NOKO_EEPROM_Disk0.ino: In function 'void loop()':

NOKO_EEPROM_Disk0:199: error: expected primary-expression before '}' token

 }

 ^

**Comment by NikolaiRadke** [comment]
Hallo!
Ist korrigiert. Es fehlte ein Semikolon in Zeile 197 hinter while(1).

Viele Grüße.
