### ISSUE TITLE
Taster

### ISSUE THREAD

**Issue by Crayfish68** [NikolaiRadke/NOKO#12]
Hallo Nikolai! Tolles Projekt, Danke für die Idee und die ganze Arbeit, die da drin steckt!!!

Ich habe eine Frage zu den Tastern: welche (Art von) Tastern hat sich als geeignet erwiesen? Ich stehe etwas auf dem Schlauch. In der Bucht finde ich den Abbildungen ähnliche (6x6x5mm), wenn ich nach "THT Taster 4 Pin" suche, frage mich aber, ob die zu klein sind. Wie groß sind die, die du benutzt hast?

PS: nachdem sich die Idee, so etwas zu Weihnachten zu machen, rumgesprochen hat, ist der Bedarf hier auf 5 gewachsen - ich bin also grad in der Massenproduktion, bzw. derzeit noch im Massen-Bestell-Prozess. Vieles kommt aus China und lümmelt sicher noch in irgendwelchen Container rum. Mal schauen :)

Thomas

**Comment by NikolaiRadke** [comment]
Meine sind haben eine Kantenlänge von ca. 1 cm - das ist ausreichend und gut zu bedienen. je größer, desto besser. Erhältlich in einschlägigen Elektronikonlineshops

Fünf Nokos! Au weia! Da wünsche ich starke Nerven ;-)
Viel Erfolg und viele Grüße!

Nikolai

**Comment by Crayfish68** [comment]
Noch eine Frage bitte:

Was genau meinst du in der Stückliste mit:
--------------------snip----------------------
2 Stiftbuchsen mit 3 Steckern, 16-polig
1 Stiftbuchse mit 2 Steckern, 10-polig
--------------------snip----------------------
?
Soweit ich das bis jetzt übersehe, brauche ich doch 2 x 16-polige Buchsen (und eben 2 x 16-polige Stecker dazu) und 1 x 10-polige Buchse (mit 1 x 10-poligem Stecker), richtig? Warum dann 2 Buchsen mit 3 Steckern bzw. 1 Buchse mit 2 Steckern??


PS: Die Dinger heißen (glaube ich) "Pfostenverbinder" - hab mir 'n Wolf gesucht, vielleicht magst du es in der Stückliste anpassen? Ich lasse mich auch gerne eines Besseren belehren ;)

Danke
Thomas

**Comment by NikolaiRadke** [comment]
Hallo Thomas,

sorry, hab Deine Nachricht übersehen.

Ich kann absolut nicht mehr nachvollziehen, was ich mir dabei gedacht habe. Ehrlich, keine Ahnung.
In NOKO sind 3 "Wannenstecker", 2x16 und 1x10-polig drin. Danke für den Hinweis. Die Stückliste und das Wiki werden überarbeitet.

Liebe Grüße,
Nikolai
