### ISSUE TITLE
Beschreiben der EEProms (write_disk0/1)

### ISSUE THREAD

**Issue by jlegen** [NikolaiRadke/NOKO#13]
Unter Windows 10 haben die beiden Programme "nach Anleitung" nichts in die EEProms geschrieben, obwohl der Ablauf (Zeit, Geblinke) normal aussah.
Das klappte erst, nachdem ich sowoho im Code, als auch im Gerätemanager den COM-Port auf 115200 Baud gesetzt hatte.
Ansonsten vielen Dank für ein wirklich interessantes Projekt! 👍

**Comment by NikolaiRadke** [comment]
Danke für den Hinweis! Wird bezeiten geprüft - sobald ich ein Windows 10-Testgerät unter den Fingern habe.

Viele Grüße!

**Comment by d1ckb31n** [comment]
Das kann ich so bestätigen. Mit der Default-Baudrate von 9600 laufen die Routinen zwar fehlerfrei durch aber Text wird scheinbar keiner geschrieben. Erst nach Anpassung der Baudrate des "Arduino-COM-Port" im Gerätemanager auf 115200 sowie der Codeanpassung in NOKO_EEPROM_Disk0.ino (Zeile 105) sowie NOKO_Disk1.ino (Zeile 22) von 

`Serial.begin(9600);`
auf
`Serial.begin(115200);`

funktioniert es einwandfrei.

**Comment by NikolaiRadke** [comment]
Kann ich auch bestätigen.
Danke für Eure Mitarbeit! Das Wiki und der Sketch werden angepasst.
