### ISSUE TITLE
MP3 Dateien

### ISSUE THREAD

**Issue by Wetimer** [NikolaiRadke/NOKO#15]
Hallo NikolaiRadke,

bin momentan ebenfalls dabei dein Noko-Projekt (darauf gestoßen über das Make-Magazin) nachzubauen. Deine Beschreibung ist sehr gut und ich komme gut voran jedoch wollte ich gerade die MP3 Dateien (https://github.com/NikolaiRadke/NOKO/tree/master/mp3) downloaden und bekam eine Fehlermeldung. Gibt es einen anderen Weg an die MP3 Dateien zu kommen oder sind die Dateien gar nicht mehr vorhanden? 

Gruß Wetimer

**Comment by NikolaiRadke** [comment]
Hallo Wetimer,

ich habe eben nachgeschaut, die Dateien können problemlos
heruntergeladen werden: Anklicken, z.B. 001.mp3, dann rechts auf
"Download", oder das alternativ das Git klonen, oder einfach alles auf
der Startseite vom NOKO-Repository mit dem grünen Button "Clone oder
download" herunterladen.

Aber um Sicher zu gehen, habe ich die Dateien gezipt und auf meinen
Webserver geladen, da sollte nichts schief gehen:
http://www.nikolairadke.de/NOKO/noko.zip

Viel Erfolg und viele Grüße,

Nikolai

-- 

	*Nikolai Radke*

Tel.  : 0171 401 22 69
Mail: kontakt@nikolairadke.de <mailto:kontakt@nikolairadke.de>
Web: http://www.nikolairadke.de

**Comment by Wetimer** [comment]
Hallo Nikolai,

vielen Dank für die schnelle Antwort! 
Danke fürs zippen, hat problemlos geklappt!

PS: Habe mit dem Programm kicad ein PCB erstellt für die Noko-Schaltung (alles auf einer Platine). Sobald ich es getestet habe ob alles so funktioniert wie es soll kann ich es gerne zur Verfügung stellen falls Interesse besteht ?!

Gruß Wetimer

**Comment by NikolaiRadke** [comment]
Hallo nochmal.

"Interesse" ist stark untertrieben :-)
Sehr gern!


Liebe Grüße,

Nikolai


-- 

	*Nikolai Radke*

Tel.  : 0171 401 22 69
Mail: kontakt@nikolairadke.de <mailto:kontakt@nikolairadke.de>
Web: http://www.nikolairadke.de

**Comment by Wetimer** [comment]
Ok dann melde ich mich nochmal sobald es fertig ist :)
