### ISSUE TITLE
Obere Leiterplatte Lautsprecher Anschlüsse

### ISSUE THREAD

**Issue by Crayfish68** [NikolaiRadke/NOKO#17]
Hallo Nikolai

Noch eine Detailfrage: 

![687474703a2f2f7777772e6e696b6f6c61697261646b652e64652f4e4f4b4f2f4e4f4b4f5f6c61796f75745f736d616c6c5f77696b692e706e67](https://user-images.githubusercontent.com/22168209/32104091-54ad9e74-bb23-11e7-9d62-d0eee81b9d5f.png)

(das ist hier:  https://camo.githubusercontent.com/beaceb80ccfa7fbee1aa4dac055786602f59c68a/687474703a2f2f7777772e6e696b6f6c61697261646b652e64652f4e4f4b4f2f4e4f4b4f5f6c61796f75745f736d616c6c5f77696b692e706e67)

Hier sind zwischen dem HC-SR04 und dem Wannenstecker zwei Leiterbahnen _nicht_ getrennt (M und N). Allerdings liegen da bei mir jetzt Echo und Trigger vom HC-SR04 drauf (an den 4 Pins habe ich den Sonsor sozusagen befestig), so habe ich es verstanden. Das war dann aber gar nicht so gemeint, oder? Denn an den beiden Pins des Wannensteckers werden ja dann R- und L+ (von den Lautsprechern).

Also, doch trennen, richtig?

vG
Thomas
PS: das war doch bestimmt mal so gedacht, das Echo und Tigger direkt zum Wannenstecker runtergezogen werden und R+- und L+- über andere SteckerPins zur Hauptplatine gehen ... aber dann hat Noko geniest?

**Comment by NikolaiRadke** [comment]
Hallo Thomas!

Ich habe gerade schrecklich viel zu tun, aber ich werde wohl heute Abend dazu kommen, Deine Fragen zu beantworten.

Liebe Grüße,

Nikolai

**Comment by NikolaiRadke** [comment]
Au backe.
Da habe ich aber einen dummen Fehler gemacht, Ich befürchte ich habe da sogar mal verschlimmbessert. Ja, der Stecker ist verrutscht. Ich muss wohl alle Grafiken neu erstellen...

Danke für den Hinweis!!

**Comment by Crayfish68** [comment]
Mh, 'Stecker verrutscht' kann, wenn ich das alles richtig sehe, eigentlich nicht sein, denn die Anschlüsse (+, -, SCL, SDA, A0, ...) stimmen ansonsten mit der Belegung von S1 auf der Hauptplatine überein ... auch die Lautsprecher. Aus meiner Sicht sollte eine Trennung der Leiterbahnen hier reichen.

vG
Thomas

Es sei denn, ich sehe hier irgend etwas anderes nicht...

vG
Thomas

**Comment by NikolaiRadke** [comment]
Es war mal angedacht, Trigger und Echo direkt hinzuführen, aber dann habe ich beim Bauen einen Fehler gemacht. Bis das Wiki überarbeitet ist, mache einfach die Unterbrechnungsline unter dem Sensor durchgängig. Ich habe die restliche Verdrahtung im Wiki angeschaut, die müsste so eigentlich funktionieren.

**Comment by NikolaiRadke** [comment]
ARGH! Da warst Du 3 Sekunden schneller :-D

**Comment by Crayfish68** [comment]
Gut, jetzt poltert mir grad ein riesiger Brocken vom Herzen, sollte eigentlich in ganz Berlin zu hören gewesen sein ;)  Und das an Halloween!

Dann werde ich mich mal weiter durchkämpfen.


:)

vG
Thomas

**Comment by NikolaiRadke** [comment]
Ja, habe ich hier in Weißensee auch gehört. Dachte, es war ein Böller. 
Viel Erfolg weiterhin! 

Das Issue bleibt erstmal offen, bis die Grafiken korrigiert sind.

**Comment by NikolaiRadke** [comment]
Ist korrigiert!
