### ISSUE TITLE
Hauptplatine im Wiki

### ISSUE THREAD

**Issue by Crayfish68** [NikolaiRadke/NOKO#19]
Und nochwas:

Im Wiki auf der Seite "Hauptplatine" scheint irgendwas nicht zu stimmen. Von unten sieht es so aus:

![grafik](https://user-images.githubusercontent.com/22168209/32189186-4964a970-bdaa-11e7-8e55-608bbf243fe1.png)

Von oben sieht es so aus:

![grafik](https://user-images.githubusercontent.com/22168209/32189259-88605886-bdaa-11e7-87e8-6209dc4aa5bc.png)

Also, müssen da jetzt 3 oder nur 2 Leiterbahnen getrennt werden?

vG
Thomas

**Comment by NikolaiRadke** [comment]
Auch hier ein dickes Danke, die Unterbrechung ist eigentlich überflüssig, sofern die Verbindung in der Grafik bei 4_1 Stromversorgung zwischen VIN+ des MP3608 und BAT+ vom TP4056 um eins nach unten versetzt wird. Die Grafik werde ich gleich korrigieren.

**Comment by NikolaiRadke** [comment]
Nein, ich habe mich entschieden, die Unterbrechung in der oberen Grafik einzufügen. Das ist einfacher, als alle anderen Grafiken neu zu bearbeiten...

**Comment by Crayfish68** [comment]
Ok, das ist für mich auch einfacher, ich hatte es schon unterbrochen und dann wieder gebrückt. Ich nehme die Brücke jetzt einfach raus.

vG
Thomas

**Comment by NikolaiRadke** [comment]
Prima. Freut mich.
Ein schönes Gefühl, ein Issue zu schließen :-)
