### ISSUE TITLE
Which licence?

### ISSUE THREAD

**Issue by NikolaiRadke** [NikolaiRadke/NOKO#2]
Ich habe keine Ahnung, welches Lizenzmodell ich wählen soll. Die meisten verwendeten Bibliotheken im Quelltext verwenden GPL v3, einige MIT. Jemand riet mit zu APACHE 2.0 - ich habe aber keine Ahnung, warum. 

Vielleicht kann mich jemand aufklären?

**Comment by StephanSST** [comment]
Ich kenne auch nicht alle drei, weiss aber, dass MIT die einfachste ist. Da darf man alles, muss aber auf Deinen Code bzw. Deine Lizenz zurückverweisen.

So wie ich Apache 2.0 verstanden habe, würde diese Lizenz verbieten, dass ein anderer Deinen Code patentieren lässt. Aber da bin ich auf Glatteis. 

Ich würde also sagen, wenn Du nicht bzw. nie vor hast, mit Noko Geld zu verdienen, dann nimm MIT.

**Comment by NikolaiRadke** [comment]
Hm. Mein Code ist eher auf Grundstudium Informatik-Niveau, aber alleine schon aus Verlagsgründen möchte ich doch die Rechte daran behalten. Dann kommt also eher Apache in Frage.

Danke für die Info!

**Comment by hkuhn42** [comment]
Apache / BSD erlaubt jedem alles (ändern,neu veröffentlichen etc.) , solange er deine Copyright Disclaimer nicht entfernt und ist damit ziemlich offen.
Falls Du Zeit zum lesen hast, gibt es bei [Heise](http://www.heise.de/ct/artikel/Open-Source-Lizenzen-221957.html) eine relativ gute Übersicht der Unterschiede.

**Comment by NikolaiRadke** [comment]
Danke für den Link!
