### ISSUE TITLE
Radio Antenne

### ISSUE THREAD

**Issue by Crayfish68** [NikolaiRadke/NOKO#20]
Hi Nikolai

Sorry, ich arbeite mich durch und dann kommen die Fragen so dahergetrödelt. Zum Radio: du sagst unter "4.3 Verstärker", dass die Antenne an den Pin zwischen den beiden Kanälen angeschlossen wird. Damit meinst du diesen Pin hier?

![image](https://user-images.githubusercontent.com/22168209/32199273-1a1272d4-bdcc-11e7-9162-bcb5b2830c29.png)

das mit der Unterbrechung zwischen L1 und C5 wird spaßig - ich sollte mir ein Mikroskop zulegen!

vG
Thomas

**Comment by NikolaiRadke** [comment]
Lieber Thomas,

die Dokumentation im Wiki ist in der Tat da etwas... defizitär, das werde ich ergänzen.
Ja, die Antenne soll an genau diesen Pin. Die Wurfantenne soll 1/4 von 3m = 0,75m lang sein.

Die Unterbrechung trennt einen Eingangsfilter aus Kondensator und Spule. Dadurch verbessert sich der Empfang. Das geht ganz gut mit einem Skalpell oder etwas brachialer mit einem Teppichmesser. Wenn das zu fummelig ist, kann der Filter auch drin bleiben.

**Comment by Crayfish68** [comment]
Hi Nikolai

Das ist ja dann doch leichter gewesen, als ich gedacht habe. Der Tip mit dem Skalpell ist Gold wert! Manchmal kommt man einfach nicht auf die einfachsten Sachen.

Leider habe ich zu dem Radio-Modul keinen Schaltplan/Bestückungsplan gefunden, könnte mir denken, dass es auch reicht entweder L1 oder C5 zu entfernen?

Im Wiki würde es ausreichen, wenn du das Bild von mir oben einfügst, ich denke, dann ist es klar. Der Antennenanschluss war wirklich das einzige, was etwas unklar war. Hiermit übertrage ich dir vollständig und unwiderruflich die Rechte an dem Bild oben! ;)


vG
Thomas

**Comment by NikolaiRadke** [comment]
Ich habe dann aus Konsistenzgründen eine Grafik mit einem grünen Modul erstellt. Wiki ist ergänzt. Danke für den Hinweis!
