### ISSUE TITLE
NOKO bleibt stumm?

### ISSUE THREAD

**Issue by Crayfish68** [NikolaiRadke/NOKO#21]
Hallo Nikolai

Ich brauche noch einmal moralische Unterstützung! Und Hilfe! Nachdem ich mich jetzt durch die Audio-Verbindungen (Teil 4.3: Verstärker) gekämpft habe, wäre mein erster NOKO eigentlich fertig - nur bleibt er leider stumm. Kein Pieps. Momentan stehe ich ein bisschen auf dem Schlauch, warum das sein könnte. Wenn ich in das Menü -> Noko stellen -> weiter... gehe, und dort versuche das "Stumm [X]" zu deaktivieren (so, dass er eben _nicht_ mehr stumm ist), dann überlegt er 2 Sekunden und dann kommt das X wieder. Ich kann grad den Fehler nicht sehen - hättest du einen Tipp für mich?

Im I2C Bus sieht Noko alles, was er soll (x10x3Fx50x57x68), Spannungen (6.5V) sind da, hab jetzt grad keine Idee mehr, was ich noch falsch gemacht haben könnte. Übersehe ich irgendetwas an der Bedienung?

vG
Thomas

![img_1725](https://user-images.githubusercontent.com/22168209/32413143-7f2697a2-c20b-11e7-87d5-9d2763636d37.png)

**Comment by NikolaiRadke** [comment]
Hallo Thomas!
Morgen Abend schaue ich mir das mal in Ruhe an. Komisch.

**Comment by Crayfish68** [comment]
Jetzt ist bei mir auch Winter ;)

Einen Fehler in der Verdrahtung habe ich grad noch gefunden: das MOSFET Gate ging an D8 und nicht D6. Das habe ich jetzt berichtigt, aber trotzdem geht es (noch) nicht, selbes Fehlerbild. (https://photos.app.goo.gl/k7eFVjTP8my8jkH93)

Mir ist aber auch grad noch aufgefallen(!), dass ich die USB Verbindungen zum MP3 Modul und Arduino noch nicht dran habe! Ich dachte, die brauche nur zum Anschluss an den PC nachher. Kann es sein, dass der Arduino und das MP3-Module darüber ihre Versorgungsspannung bekommen, zumindest solange der Potischalter aus ist? Ich hätte jetzt angenommen, die kämen über den 5V Bus über StepUp Wandler und dann 5V Regler - aber die sind ja dann aus!? Die Seite 3 des Schaltplanes hat mich da reingelegt, da ist nämlich rehts (Arduino und MP3 USB) nur D+ und D-.
Trotzdem, wenn ich den Potischalter einschalte ... _sollte_ es ja gehen. Ich vermute, das irgendetwas immer noch nicht stimmt.

Nunja, ich wollte Geld sparen, die USB-Selbstlöt-Stecker sind noch auf dem Weg aus Fernost, hier im Abendland kosten die (konfektionierten) ein Vermögen (4€/Stck vs. 1€/10Stck), aber ich bestelle dann mal 2 bei Reichelt, brauche eh noch Zeugs.

vG
Thomas

**Comment by NikolaiRadke** [comment]
Lieber Thomas,

das sich "Stumm" nicht ausstellen lässt, ist schon sehr komisch, da dieser Zusand nur über dieses Menü geschaltet werden kann. Wenn Stumm, also die Variable quiet=true ist, müsste NOKO ein großes S im Display neben der Uhrzeit haben.

Ersetze doch mal bitte in Zeite 283 "quiet=read_EEPROM(1);" durch "quiet=false;". Dann miss mal D6 bzw. das MOSFET-Gate. Beim Einschalten muss NOKO zwei Töne von sich geben und dabei D6 auf LOW ziehen. Ist der Verstärker aus, ist D6 HIGH.

NOKO bezieht seinen Strom ausschließlich über den Akku. Ich habe sowohl beim MP3-Modul als auch beim Arduino nur die Datenleitungen D+ und D- des Hubs verlötet. Die Versorgung der beiden kommt, wie vermutet, über die 5V des Regulators. Somit ist NOKO nicht in einem schrecklichen Dämmerzustand, wenn Der Akku geladen wird. Die USB-Verbindungen werden aber im Betrieb nicht benötigt. Die kommen nur zum Einsatz, wenn NOKO an den Computer angeschlossen wird, um eine neue Software auzuspielen oder die SD-Karte des MP3-Moduls zu beschreiben.

Die Winkelstecker kosten hier schrecklich viel Geld, ich weiß. Wären da nicht private und berufliche Pflichten, würde ich NOKO-Teile im eigenen Shop für kleines Geld anbieten. Oh grausames Schicksal.

Dran bleiben!

Viele Grüße,
Nikolai

**Comment by Crayfish68** [comment]
Hallo Nikolai

Ich habe jetzt ein paar Tage probiert, ich komme derzeit einfach nicht weiter. Es ist ein Hardware Problem an der oberen Leiterplatte. Nach dem Herausnehmen dieser Platine (aus der Befestigung), ging es plötzlich – aber nur ganz kurz. Wenn ich sie jetzt wieder einsetze und mit dem Kabel (S1) verbinde, dann brechen meine 5V plötzlich ein. Manchmal. Wenn ich sie dann nochmal herausnehme und wieder einsetze, geht es (ohne Ton). Dann wieder nicht. ... Irgendwo ist noch ein Wackler oder eine Brücke, aber es ist sehr schwierig zu finden. Das Einfachste wäre wohl, diese Platine noch einmal zu machen, jetzt weiß ich ja wie es geht ;)

Aber, ich denke, ich warte aber jetzt erst einmal auf meine Leiterplatten aus China. Sie sollten nächste Woche ankommen, wenn alles gut geht. Ich denke, dass ich damit insgesamt besser fahre. Durch-testen und bauen muss ich die dann sowieso, insgesamt denke ich, wird das der einfachere Weg sein. Also, mach hier ersteinmal zu, der Fehler liegt so oder so bei mir.

Mhmpf :/


vG
Crayfish
