### ISSUE TITLE
SDL vs. SCL

### ISSUE THREAD

**Issue by Crayfish68** [NikolaiRadke/NOKO#22]
Weil du grad am ändern bist, hier noch ein ganz, ganz, ganz, ganz kleiner Typo für dich: auf diesem Link (https://github.com/NikolaiRadke/NOKO/blob/master/schematics/NOKO_layout_up_data.png) steht S_D_L, an Stelle von S_C_L!

![grafik](https://user-images.githubusercontent.com/22168209/32692228-6b35c64c-c714-11e7-9072-861a127af9ac.png)

vG
Thomas
PS: Leiterplatte kommt, habe noch einige Verbesserungen eingebaut...

**Comment by NikolaiRadke** [comment]
Ist korrigiert!
