### ISSUE TITLE
NOKO Gehäuse

### ISSUE THREAD

**Issue by Crayfish68** [NikolaiRadke/NOKO#23]
Hallo

Ich habe vor Monaten ein passendes Gehäuse für NOKO bei W**lw*rth gefunden. Ich glaube, es handelte sich um den Vorgänger von dieser Snackbox hier:

![grafik](https://user-images.githubusercontent.com/22168209/33432819-b59ed592-d5d9-11e7-9ef0-ecf646bd34fe.png)
(Snackbox flach 387208)

Die EAN Nummer auf meiner Box ist 387900

Allerdings bekomme ich es nirgendwo mehr. In allen 1€ Shops gibt es dieselben Boxen, die ich derzeit habe, sind mir eigentlich locker 1cm zu dick. Die, die flach genug wären, sind zu klein, da passt z.B. das LCD Display nicht rein. Das o.g. gefällt mir noch am ehesten.

Hat jemand entweder einen Tip, wo ich die finden kann oder eine andere Idee für ein passendes Gehäuse? Ich habe auch grad den Hersteller angeschrieben, vielleicht wird mir ja geantwortet, wo ich diese käuflich erwerben kann. Bei Erfolg sage ich Bescheid.

Danke
vG
Crayfish

**Comment by NikolaiRadke** [comment]
Ja, die kommt mir bekannt vor...
Da hast Du doch glatt meinen nächsten Aufruf vorweg genommen: Ein passendes 3D-gedrucktes Gehäuse, in das die Module ohne bohren und sägen eingelassen werden können.

Die Dosen habe ich damals aus Tedox rausgeholt. Oder war es Poco?

**Comment by andy5macht** [comment]
Ich habe Zugriff auf einen 3D-Drucker. Nur im Konstruieren bin ich kein Profi. Wenn ich die ganze Hardware zusammen habe werde ich mich nach den Abmaßen bemühen. (oder hat da jemand schon die nötigen Daten?)
Und dann ein einfaches Gehäuse konstruieren.

**Comment by Crayfish68** [comment]
Der Hersteller hat mir tatsächlich geantwortet, womit ich im Leben nicht gerechnet hätte. Diese Boxen gibt es bei Kaufland derzeit - sie hat mich auch auf eine Lidl Aktion im Januar hingewiesen ;)

Nikolai, wie ist denn deine Meinung zu diesen Boxen?
![grafik](https://user-images.githubusercontent.com/22168209/33560299-af164104-d90f-11e7-9ea2-c5654e97fa3a.png)
![grafik](https://user-images.githubusercontent.com/22168209/33560318-b76a7b90-d90f-11e7-88c0-2c1395e5b282.png)

Die sind nochmal deutlich kleiner (ca. 16cm x 11cm x 4cm). Die Leiterplatte würde ich auf die Größe bekommen (ca. 8cm x 13cm), sofern ich den 5V Regelkreis rauslassen kann (Regler + 3 Elkos). Das Display, Sensor, Lautsprecher müssten dann in den Boden, die Leiterplatte in den Deckel. Ich bin mir nicht so ganz sicher, ob das passt, könnte aber eine gute Idee sein? Die 4cm Höhe wären das Mindestmaß, rein rechnerisch. Vielleicht schaust du dir das mal an, falls nicht schon geschehen.

Ja, oder halt 3D-Druck ... *träum*

Crayfish

**Comment by NikolaiRadke** [comment]
Diese Dose habe ich auch hier rumliegen, allerdings war sie mir zu hoch und nicht breit genug.
Aber sehr großartig ist, dass Du eine Antwort bekommen hast!!

So eine in Lila hast Du doch für Deinen platinenlosen NOKO verwendet?
Bei dem weißen Gehäuse gefällt mir die Anordnung nicht, da ich bei mir sehr viel wert auf NOKOs Äußeres lege und dort die Schnittvorlage nicht funktioniert. Aber gegen Eigenkreativität ist natütlich nichts einzuwenden :-)

Ich schaue mich auch nochmal nach geeignete Dosen um.

**Comment by Crayfish68** [comment]
Sorry, ich hätte etwas klarer sein sollen. Noch einmal von vorn:

Ich habe derzeit 3 verschieden Boxen hier:
![grafik](https://user-images.githubusercontent.com/22168209/33712981-a1ecdf56-db49-11e7-8ea7-8aa39878febb.png)
Von links nach rechts:
* Links ist die weiße (eigentlich hell-türkis), in der ich meinen ersten NOKO mit Leiterplatte verbaut habe. Die ist allerdings mit 5cm mir persönlich zu dick.
* In der Mitte ist die von dir ursprünglich vorgeschlagene Box in der ich meine aller ersten NOKO - in lila - verbaut hatte. Die Außenmaße sind 18,5cm x 14cm x 4cm. Damit baue ich jetzt meine 5 NOKOs fertig, soweit klar.
* Rechts ist jetzt eine deutlich kleinere Snackbox. Die Außenmaße sind da 16cm x 11cm x 4cm. Die gibt es derzeit in jedem, gut sortierten Fach-Euro-Shop. Der direkte Vergleich zeigt es besser:

![grafik](https://user-images.githubusercontent.com/22168209/33713121-4135145c-db4a-11e7-915a-e6049ea79246.png)
![grafik](https://user-images.githubusercontent.com/22168209/33713128-48b85d1a-db4a-11e7-9662-25227d585044.png)
Die Frage ist jetzt, aus deiner NOKO Bauerfahrung, würde das Display, Lautsprecher und Ultraschall-Sensor in die kleinere Box passen? Ich selbst denke es passt. Ganz knapp zwar, aber passt.

Die Leiterplatte bringe ich auf die entsprechende Größe in der nächsten Version. Ist eigentlich schon zu 90% fertig. Ich hoffe, der 5V Regler kann draußen bleiben, ich werde das mit dem nächsten mal testen (kann ich ja einfach weglassen und überbrücken, auch auf der derzeitigen Platine).

Und ja, ich habe mich mit den neuen Boxen jetzt etwas näher an deiner Orginalvorlage orientiert. Die weiße gefällt mir so wie sie ist/war auch nicht.

viele Grüße
Crayfish


PS: haben wir eigentlich grad eine Diskussion um Brotboxen?

**Comment by NikolaiRadke** [comment]
Hmm... Beim Entwurf ging es eigentlich nur darum, Alle Bauteile auf der Platine unterzubringen. Bei meiner wilden Verdrahtung kam ich auf die Maße der Platine und habe dann entsprechend nach passenden Dosen gesucht. Probier es doch mal aus - allerdings passt das Schnittmuster nicht mehr richtig, das müsste etwas verkleinert werden, was ja nicht schlecht wäre.

Ja, wir reden über Brotdosen, genau genommen 1€-Brotdosen :-D 
Und manche Leute nehmen sogar mit den Herstellern Kontakt auf!
