### ISSUE TITLE
USB Hub

### ISSUE THREAD

**Issue by bencha** [NikolaiRadke/NOKO#24]
Hallo Zusammen,

da ich gerade am Basteln bin und zum Glück schon die einfache Version und zwar das Board von Crayfish68 verwende, ist mir trotzdem das USB Hub ein Dorn im Auge und ich bin auf die Suche gegangen.
Dabei habe ich heute das folgende Nano USB Hub mit 2 Ports auf tindie.com gefunden.
Ob es was taugt, weiß ich leider noch nicht oder vielleicht ist jemand gerade auf der Suche nach einem USB Hub und möchte dieses mal testen. :-)
Leider ist es auch deutlich teurer, als alle anderen. :-(

https://www.tindie.com/products/mux/nanohub-tiny-usb-hub-for-hacking-projects/

@crayfish68: Wenn das USB Hub etwas taugt, dann könnte das eventuell mit in das PCB Board eingeplant werden, oder?

Grüße
Benjamin

@NikolaiRadke: Ich habe gesehen, Du hast auch ein neues Board in Verwendung. Kannst Du uns mal eine Beschreibung oder ein Link dazu hinterlassen?

**Comment by NikolaiRadke** [comment]
Der Hub ist prima, mir persönlich allerdings zu teuer. 
Ich werde ihn im künftigen PCB-Wiki jedoch gerne als Alternative aufnehmen (und mir heimlich doch einen kaufen ;-) ).

Ich habe ein neues Board? Ich verwende das, das ich von Crayfish68 zugeschickt bekommen habe...

**Comment by bencha** [comment]
Mit "neues Board" meinte ich das USB Hub, dass Du auf crayfishs Platine verwendet hast.

**Comment by NikolaiRadke** [comment]
Achso. Das teste ich gerade, gibt es ab 2,70€. Ich bin mir noch nicht sicher, ob das Schrumpfschlauchgefummel nerviger ist, oder das Büchsenauslöten,

https://de.aliexpress.com/item/DC-5-V-USB-Hub-USB2-0-Hub-4-Female-Hub-USB-Expansion-Board-Modul/32845109447.html?spm=a2g0x.search0104.3.15.KZLvCy&ws_ab_test=searchweb0_0%2Csearchweb201602_2_10320_10152_10321_10065_10151_10344_10068_10342_10547_10325_10343_51102_10546_10340_10548_10341_10194_10084_10083_10304_10307_10180_10312_10313_10059_10314_10184_10534_100031_10604_10103_10605_10186_10594_10142%2Csearchweb201603_25%2CppcSwitch_5&algo_expid=8cd5bab2-64bb-4311-8d94-690b0b36bd85-2&algo_pvid=8cd5bab2-64bb-4311-8d94-690b0b36bd85&rmStoreLevelAB=5

Oder auch in der Buch nach "USB Hub Board" suchen.

**Comment by Crayfish68** [comment]
Den Nano-USB-Hub finde ich schon genial - allerdings (genau wie Nikolai) deutlich zu teuer. Ich komme beim NOKO auf Gesamtkosten von etwa 100€ - 120€ (auch stark abhängig davon, ob man schon Bastler ist, sprich Kabel hat, Crimpzange, Löt-Zubehör, Schrauben, etc.).
Wenn jetzt nur der USB Hub davon schon 10% einnimmt, ist das in Relation zu viel.

Ich hatte auch mal nach USB Chips (ICs) geschaut. Aber man kommt erstens nicht auf den Preis von 2€ bis 3€, dann braucht es immer noch Außenbeschaltung und es sind SMD Packages, die nicht einfach zu löten sind.

Meine Erfahrung mit dem Micro USB Hub, der im Wiki steht: man sollte die schwarze Isolierung der Anschlüsse so dicht am Gehäuse wie möglich abisolieren/entfernen (wenn das jetzt Sinn mach). Dann etwas Muße nehmen zum schrumpfen und es passt. Ich habe ihn am Ende dann eher so schräg (45°) reingesetzt (siehe auch Bild im anderen Issue).

Ich habe mir noch so paar der kleineren Micro USB Hubs mit 2 Ports bestellt, die sollten auf dem Weg sein. Ich werde mal einen aufknacken, vielleicht kann man das Innere einfach(er) auf das Board bringen?

Crayfish

**Comment by Crayfish68** [comment]
Es gibt Neuigkeiten:

Bei mir sind grad die kleinen 2-Port-USB-Hubs aus Xingyuan (North) angekommen. Ich würde mal fast ganz doll stark dafür plädieren. Hier mal ein Foto:

![grafik](https://user-images.githubusercontent.com/22168209/34770285-e505ab7a-f600-11e7-93ed-1e3e75b9292e.png)

Man kann die ganz easy aufknacken, einfach mit einem Seitenschneider vorsichtig an einer Ecke, wahrscheinlich kann man sie mit etwas mehr Geschick als ich auch einfach aufhebeln. Von Innen sieht es dann so aus:

![grafik](https://user-images.githubusercontent.com/22168209/34770274-da676122-f600-11e7-8320-35e54dee6616.png)

Die Platine ist 18,3mm x 21,8mm groß. Da kann man ohne Probleme die +/-/D+/D- jeweils ein kurzes Kabel anlöten und dann auf die Leiterplatte verbinden. Da würde ich dann entsprechend den passenden Footprint für anlegen.
Als einziger USB Anschluss, der dann händisch zu machen wäre, bliebe dann der Arduino. Wenn ich den auf der Leiterplatte drehe, dann bräuchte es noch nicht mal einen gewinkelten Stecker, sondern man kann einen beliebigen (graden) nehmen. Ist günstiger und einfacher zu bekommen.

Mit dieser Platine traue ich mir auch ganz locker zu, die Platine auf die Größe von 80x130mm zu bekommen, oder noch kleiner. Kleiner kann ja nicht schaden. Vielleicht 80x100mm, dann kosten sie fast nichts mehr.

Was meint ihr? Ich habe ein paar mehr bestellt (ausversehen), wenn ihr also einen zur Ansicht haben wollt - also @NikolaiRadke und @bencha jetzt :) - kann ich jeweils einen in einen Brief stecken und zu euch schicken, dann könnt ihr euch selbst ein Bild machen.


vG
Crayfish

**Comment by NikolaiRadke** [comment]
Das ist so ziemlich genau das, was ich seit drei Jahren suche!
Sehr schön. Über Post würde ich mich freuen und den Hub dann um Wiki übernehmen.

**Comment by jlegen** [comment]
Ali, Suche nach "2 Port Hub", erste Seite:
https://de.aliexpress.com/item/Hot-New-Design-High-Quality-Portable-USB-3-1-Type-C-USB-C-To-Dual-2/32804431620.html?spm=a2g0x.search0104.3.137.32ebe1b9WtCxGS

sieht zumindest sehr ähnlich aus, Order läuft... :-)

**Comment by Crayfish68** [comment]
Das wird derselbe sein. Ich hatte bei eBay (China) bestellt: https://www.ebay.de/itm/Micro-USB-Stecker-OTG-Hub-f%C3%BCr-Smartphone-Handy-Tablets-On-The-Go-Adapter-Kabel/162650973982?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

Hat den eigentlich schon jemand von euch probiert? Ober der was taugt in dem Zusammenhang? Na, das wär's jetzt der Brüller ... :/

**Comment by NikolaiRadke** [comment]
Ali und ich werden keine Freunde. Ich habe dort zweimal was bestellt, beide Male ist nichts angekommen. Ich bin wohl der einzige weit und breit, aber jetzt ein gebranntes Kind :-)
