### ISSUE TITLE
Wie schliesse ich den USB-Hub auf der Platine 2.0 an?

### ISSUE THREAD

**Issue by GhostGirl16** [NikolaiRadke/Noko#39]
Hallo, 
auf meinem Noko (Platine 2.0) muss nun der USB-Hub eingelötet werden. 
![ganzePlatine](https://user-images.githubusercontent.com/46863755/57179356-6d959e00-6e7d-11e9-812e-ac4d204b84d3.JPG)

Welcher Pin des USB-Hubs muss mit welchem Pin der Platine zusammen gelötet werden? In den anderen Threads ist nicht immer ganz klar wer welche Platinen Version verwendet, weshalb ich nun etwas verwirrt bin.
![USB_Hub](https://user-images.githubusercontent.com/46863755/57179357-77b79c80-6e7d-11e9-9238-f209f648a3fa.JPG)

Danke für Eure Unterstützung
Natalie

**Comment by NikolaiRadke** [comment]
Hallo Natalie,

mit dieser Platinenversion ist die Pin-Belegung korrigiert worden. 5V an 5V DP an D+, DM an D-, GND an GND. Alles, wie es sein soll.

Naja, fast. Dieser Hub macht leider Probleme. Bei einem Noko funktioniert er, bei etlichen anderen nicht. Daher empfehle ich den etwas größeren Hub aus NOKO 1, auch wenn der nicht auf die Platine gelötet werden kann.

 Probiere es aus, in der Software gibt es unter NOKO stellen den Menüpunkt Equalizer und Upload, dann könnte es möglich sein, da so keine Steuersignale an des Modul gesendet werden. Konnte ich bisher jedoch nicht testen.

Dran bleiben, das sieht ja alles schon ganz toll aus!

Liebe Grüße,

Nikolai

**Comment by GhostGirl16** [comment]
Vielen Dank für die Antwort. Ich werde es gerne ausprobieren.
