### ISSUE TITLE
Kein Issue, eher eine Frage ...

### ISSUE THREAD

**Issue by teuler** [NikolaiRadke/NOKO#6]
Hi, mir gefällt das Projekt sehr gut. Eine Frage zum Verstärker: Ich verwende ein DAB-Radio-Modul und hatte große Probleme mit dem Empfang, sobald ich die Verstärkerschaltung (mit dem TDA7053a) anschloss. Nach etwas 'rumprobieren fand ich heraus, dass das Step Up-Modul (MT3608) für die Störungen verantwortlich ist und der Verstärker (ich betreibe ihn allerdings Mono) auch mit stabilisierten 5V aus einem USB-Hub läuft. Was spricht dagegen, den Verstärker mit 5V zu betreiben?
Vielen Dank und Grüsse,
Thomas

**Comment by NikolaiRadke** [comment]
Hallo Thomas,

entschuldige die späte Antwort, Deine Mail hat der Spamfilter gefressen.
Gegen 5V spricht die Klangqualität. Erst ab etwas mehr als 6V war der 
Verstärker einigermaßen laut und klirrfrei. Wird auch im Datenblatt 
empfohlen. Lauffähig ist er aber ab 4,5V, 5V sollten also auch gehen, 
aber dann eben nicht kräftig krachen. Beim USB-Hub darauf achten, dass 
er mindestens 1A bei Spitzenlast gibt. Die Ports an meinen Computern 
gehen da schon lange in die Knie.

Liebe Grüße,

Nikolai





-- 

	*Nikolai Radke*

Tel.  : 0171 401 22 69
Mail: kontakt@nikolairadke.de <mailto:kontakt@nikolairadke.de>
Web: http://www.nikolairadke.de

**Comment by teuler** [comment]
Hallo Nikolai,

danke für die Nachricht und die Info.
Ich kann kein Klirren feststellen und laut genug ist der Verstärker auch. Ich denke, ich bleibe erstmal bei 5V - ich habe bisher keinen Spannungswandler (5V -> 6.5V oder höher) gefunden, der nicht den DAB Receiver massiv stört. Beim USB-Hub habe ich darauf geachtet, dass er ein externes Netzteil mit mindestens 3A mitbringt.

Beste Grüsse,
Thomas

**Comment by NikolaiRadke** [comment]
Da bin ich gespannt, halt mich auf dem Laufenden.
Was ist das für ein DAB-Modul?

**Comment by teuler** [comment]
http://www.monkeyboard.org/products/85-developmentboard/80-dab-fm-digital-radio-development-board

**Comment by NikolaiRadke** [comment]
Danke für den Link. Bin gespannt, was daraus wird!

**Comment by teuler** [comment]
https://github.com/teuler/Grundig60

**Comment by NikolaiRadke** [comment]
Tolle Idee, schönes Projekt!
