### ISSUE TITLE
Limo statt Bier

### ISSUE THREAD

**Issue by salomonderossi** [NikolaiRadke/NOKO#7]
Hey, erst mal danke für das super tolle Projekt. Eine Frage hätte ich doch. Könnt Ihr bei dem mp3 `066.mp3` das Bier durch Limo ersetzen?

**Comment by NikolaiRadke** [comment]
Nein. Aber ich erstelle einfach demnächst ein zweites 066.mp3 mit Limo - dann sind beide Fraktionen zufrieden :-)

**Comment by salomonderossi** [comment]
Super. Danke <3
Das ging ja schnell. Dann fangen wir gleich mit der Arbeit an. Dann wird das auch für's Kind bis zu Weihnachten fertig ;)

Ein Kit bei dem alle Teile dabei sind kann man bei "Euch" nicht bestellen, oder?

**Comment by NikolaiRadke** [comment]
Hier ist ein alternatives 066.mp3:
https://github.com/NikolaiRadke/NOKO/tree/master/mp3/alternative

Nein, ein Kit wird es wohl nicht geben. Ich bin nur ein (semikompetenter) Bastler, mehr nicht.

**Comment by salomonderossi** [comment]
Vielen vielen Dank!
