### ISSUE TITLE
MP3 Modul JQ6500-28p

### ISSUE THREAD

**Issue by bencha** [NikolaiRadke/NOKO#8]
Hallo Nikolai,

ich klicke mir aktuell alle Bauteile für den Bau von NOKO in den Onlineshops zusammen und muss sagen, sehr aufwendig das ganze. Den Verstärker TDA7053a habe ich noch bei eBay in UK gefunden aber bei dem MP3 Modul JQ6500-28p stehe ich gerade auf dem Schlauch.
Denn es wird mir auch das Modul JQ650-28p angeboten, welche Bezeichnung ist denn nun richtig?

Ansonsten ist das ein sehr schönes Projekt, Daumen hoch!

Grüße
Ben

**Comment by NikolaiRadke** [comment]
Hallo Ben!

Das JQ6500-28p wird auch gerne mal als JQ650-28p angeboten. Ist also derselbe Typ. 
Diese Frage kam schon mal, muss ich also im Wiki mal darauf eingehen.

Viel Erfolg beim Basteln!

LG, 
Nikolai

**Comment by bencha** [comment]
Hallo Nikolai,

vielen Dank!

Grüße
Benjamin
