### ISSUE TITLE
Printrelais ST3 002 H5W alternative ?

### ISSUE THREAD

**Issue by JimmyBondi** [NikolaiRadke/NOKO#9]
Hallo Nikolai,

auch ich bin gerade dabei mir alles herauszusuchen.
Dabei ist mir aufgefallen, dass das genannte Printrelais anscheinend ebenfalls nicht mehr verfügbar ist.
Welches könnte ich denn alternativ dafür nehmen ?

Danke und Gruß,
Lars

**Comment by NikolaiRadke** [comment]
Oje... schon wieder ein Bauteil, das eingestellt wurde. Es ist zum verrückt werden.
In Frage käme vielleicht das G6K-2P 5V. Allerdings braucht dieses Relais noch eine Schutzdiode. Ich kümmere mich am Wochendende darum. Dabei ist mir auch ein Fehler im Verdrahtungsplan aufgefallen, es sind Plus und Minus, also Pin1 und Pin10 vertauscht. Interessanter Weise funktioniert es trotzdem tadellos :-)

Viele Grüße,

Nikolai

**Comment by bencha** [comment]
Diesem Thema schließ mich an, bin gespannt welche Lösung folgt.

Vorab schon mal vielen Dank
Ben

**Comment by NikolaiRadke** [comment]
Das Printrelais ist nun ein FRT8S. Dass benötigt allerdings noch eine Freilaufdiode in Sperrichtung. Hierfür reicht eine 1N4001 aus. Das Relais ist genauso groß und hat diesselbe Pinbelegung wie das ST3 002 H5W. Das Wiki wurde entsprechenend angepasst.

**Comment by bencha** [comment]
Hallo Nikolai,

erstmal vielen Dank für das Feedback, aber leider muss ich Dir sagen, Du machst es uns nicht einfach.
Ich suche nun seit 1h nach dem Printrelais und nicht mal die Dealer meines vertrauens (reichelt.de, Ebay.de, Conrad.de u. google.de) können das Relais finden. Die Freilaufdiode ist Wiederrum kein Problem.

Ich hoffe Du kannst uns auch hier weiterhelfen.

Danke und Grüße
Ben

**Comment by NikolaiRadke** [comment]
Das liegt daran, dass ich mich gerne an den entscheidenden Stellen vertippe :-)
Das Relais heißt FRT5 DC5V (Reichelt) oder FRT5 DV05V (Conrad).

Zur Strafe muss ich jetzt wieder alle entsprechenden Texte im Wiki ändern.

**Comment by NikolaiRadke** [comment]
Als Alternative zum Relais dient nun das gleich große und Pingleiche FRT5 DC5V. Allerdings benötigt dieses Relais noch eine Freilaufdiode.
